# Generated by Django 2.0.3 on 2020-03-30 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_subscription_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='scheduled_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='scheduled on'),
        ),
    ]
